### ISSUE TITLE
spike count plot does not show after simulating

### ISSUE THREAD

**Issue by terhorstd** [babsey/nest-desktop-legacy#11]
When clicking the run simulation button, the first display of  results has the raster plot filled, but the spike-count graph below is empty. When zooming into the raster plot the spike-count graph is updated and shows reasonable peaks.

Ideally all displayed plots show up directly after simulation.

**Comment by terhorstd** [comment]
Right after the simulation:
![Screenshot_area_20200507_161808](https://user-images.githubusercontent.com/19151396/81308585-3c4c4100-9082-11ea-95fd-603cbe08681c.png)

zoomed in on the raster plot as minimal as possible using the rectangular zoom tool:
![Screenshot_area_20200507_162048](https://user-images.githubusercontent.com/19151396/81308569-38202380-9082-11ea-8217-b2ebd36968f2.png)

**Comment by babsey** [comment]
Fixed in 7d5b4a90b30bc4dd238c885c6a22d3a1c9003582
