### ISSUE TITLE
Application is not available

### ISSUE THREAD

**Issue by terhorstd** [babsey/nest-desktop-legacy#12]
When going to the URL, instead of NEST Desktop or a login window showing up I sometimes get this error message:
![Screenshot_area_20200507_163859](https://user-images.githubusercontent.com/19151396/81308936-ab299a00-9082-11ea-8f84-ee0d83ffadac.png)

I noticed that eventually the tab gets redirected to the login page, when I stare at it long enough. Loging in, then sometimes works, or it just gives:

![Screenshot_area_20200507_165030](https://user-images.githubusercontent.com/19151396/81309190-f348bc80-9082-11ea-868b-3747d263a227.png)

**Comment by babsey** [comment]
Can you check if this problem still remains in NEST Desktop 2.5.0 which I released last week?

**Comment by terhorstd** [comment]
Where can I test the 2.5.0? I use https://nest-desktop.apps.hbp.eu, which currently still shows all components to be 2.4.0. Is the new release not deployed yet?

**Comment by babsey** [comment]
You can test here: https://nest-desktop-v2.apps-dev.hbp.eu/

**Comment by terhorstd** [comment]
On the apps-dev server I can't reproduce the problem. I seem to have killed the nest-server, however. Since my third login I can't simulate anything anymore...

**Comment by babsey** [comment]
Thank you for checking. 
Can you post here a screenshot of your browser console (F12 -> console), please?

**Comment by babsey** [comment]
Closed because it has been solved in other repository.
