### ISSUE TITLE
Spike count histogram bars disappearing

### ISSUE THREAD

**Issue by jasperhelleckes** [babsey/nest-desktop-legacy#7]
When making the browser window narrower, the spike count histogram bars gradually become thinner. The problem here is that at some point, they disappear completely. When setting a large simulation time (e.g. 10000ms), the browser window need to be very wide in order to see any bars.

**Comment by babsey** [comment]
Fixed in 7d5b4a90b30bc4dd238c885c6a22d3a1c9003582
